### ISSUE TITLE
Running scrumonline with external MySQL

### ISSUE THREAD

**Issue by brunowego** [chrisns/scrumonline#17]
I think something are wrong, I'm try run scrumonline with external MySQL but not are connecting and creating the migrations.

https://github.com/brunowego/cookbooks/blob/develop/scrumonline.md#external-mysql

**Comment by chrisns** [comment]
Umm. Busy this weekend, will find some time to help next week. If you fix it in the meantime please update here
Thanks!

**Comment by brunowego** [comment]
After run

```sh
docker exec -i scrumonline /bin/sh << EOSHELL
./vendor/bin/doctrine orm:schema-tool:create
./vendor/bin/doctrine orm:generate-proxies
EOSHELL
```

Works! Thanks.

**Comment by chrisns** [comment]
Ace.
Closing this issue but if you think the docs could be clearer then please PR :) thanks!
